################################################################################
# Server-Side Repo Configuration
# Only valid repo-level fields go here.
# Server-wide flags go in docker-compose.yml as environment variables.
################################################################################

repos:
  - id: /.*/
    allowed_overrides:
      - apply_requirements
      - workflow
      - delete_source_branch_on_merge
    apply_requirements: []
    allow_custom_workflows: true
    delete_source_branch_on_merge: false

workflows:
  default:
    plan:
      steps:
        - init
        - plan
    apply:
      steps:
        - apply
