#!/usr/bin/env bash
################################################################################
# setup-local.sh
# Local development setup: checks prerequisites and generates secrets
# for running Atlantis locally via Docker Compose.
#
# Usage: ./scripts/setup-local.sh
################################################################################

set -euo pipefail

echo "══════════════════════════════════════════"
echo "  Atlantis Demo — Local Setup"
echo "══════════════════════════════════════════"
echo ""

ERRORS=0

# ── Check prerequisites ──────────────────────────────────────────────────────

check_cmd() {
  local cmd="$1"
  local install_hint="$2"
  if command -v "${cmd}" &>/dev/null; then
    local version
    version=$("${cmd}" --version 2>&1 | head -1)
    echo "  ✅ ${cmd}: ${version}"
  else
    echo "  ❌ ${cmd}: NOT FOUND — ${install_hint}"
    ERRORS=$((ERRORS + 1))
  fi
}

echo "Checking prerequisites..."
echo ""
check_cmd "terraform"  "https://developer.hashicorp.com/terraform/install"
check_cmd "docker"     "https://docs.docker.com/get-docker/"
check_cmd "git"        "https://git-scm.com/downloads"
check_cmd "gh"         "https://cli.github.com/ (optional, for GitHub CLI)"
check_cmd "tflint"     "brew install tflint (optional, for linting)"
echo ""

if [[ "${ERRORS}" -gt 0 ]]; then
  echo "⚠️  ${ERRORS} prerequisite(s) missing. Install them before continuing."
  echo ""
fi

# ── Generate webhook secret ──────────────────────────────────────────────────

ENV_FILE=".env"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Generating .env file for Docker Compose..."

  WEBHOOK_SECRET=$(openssl rand -hex 20)

  cat > "${ENV_FILE}" <<EOF
# Atlantis Docker Compose Environment
# Generated by setup-local.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# GitHub credentials (fill these in)
ATLANTIS_GH_USER=your-github-username
ATLANTIS_GH_TOKEN=ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ATLANTIS_GH_WEBHOOK_SECRET=${WEBHOOK_SECRET}

# Repository allowlist (comma-separated)
ATLANTIS_REPO_ALLOWLIST=github.com/your-org/your-repo

# Atlantis server settings
ATLANTIS_PORT=4141
EOF

  echo "  ✅ Created ${ENV_FILE} with generated webhook secret"
  echo "  ⚠️  Edit ${ENV_FILE} and fill in your GitHub credentials"
else
  echo "  ℹ️  ${ENV_FILE} already exists, skipping generation"
fi

echo ""
echo "──────────────────────────────────────────"
echo "Next steps:"
echo "  1. Edit .env with your GitHub credentials"
echo "  2. Run: docker compose up"
echo "  3. Atlantis will be available at http://localhost:4141"
echo "──────────────────────────────────────────"
